//
//  ShareService.swift
//  FleetIQ
//
//  Created by GitHub Copilot on 2026-05-04.
//

import UIKit

final class ShareService {
    static let shared = ShareService()
    private init() {}

    /// Builds a formatted plain-text cost report string
    /// suitable for sharing via WhatsApp or email.
    func generateCostReportText(
        registration: String,
        lifetimeCost: Double,
        monthlyAverage: Double,
        costPerKm: Double,
        categorySplit: [String: Double]
    ) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "dd MMMM yyyy"
        let today = dateFormatter.string(from: Date())

        let totalForPercentage = categorySplit.values
            .reduce(0, +)

        var categoryLines = ""
        for (category, amount) in categorySplit
            .sorted(by: { $0.value > $1.value }) {
            let pct = totalForPercentage > 0
                ? Int((amount / totalForPercentage) * 100)
                : 0
            categoryLines += "  \(category): LKR \(formatted(amount)) (\(pct)%)\n"
        }

        return """
        ━━━━━━━━━━━━━━━━━━━━━━━━
        FleetIQ Cost Report
        Vehicle: \(registration)
        Generated: \(today)
        ━━━━━━━━━━━━━━━━━━━━━━━━
        Lifetime Total:   LKR \(formatted(lifetimeCost))
        Monthly Average:  LKR \(formatted(monthlyAverage))
        Cost Per km:      LKR \(String(format: "%.2f", costPerKm))
        ━━━━━━━━━━━━━━━━━━━━━━━━
        Category Breakdown:
        \(categoryLines)━━━━━━━━━━━━━━━━━━━━━━━━
        Generated by FleetIQ
        """
    }

    /// Presents UIActivityViewController to share text.
    /// Works from any screen. No view controller reference needed.
    func shareText(_ text: String) {
        let activityVC = UIActivityViewController(
            activityItems: [text],
            applicationActivities: nil)

        guard let windowScene = UIApplication.shared
            .connectedScenes
            .first(where: {
                $0.activationState == .foregroundActive
            }) as? UIWindowScene,
            let rootVC = windowScene.windows
                .first(where: { $0.isKeyWindow })?
                .rootViewController
        else { return }

        var topVC = rootVC
        while let presented = topVC.presentedViewController {
            topVC = presented
        }

        if let popover = activityVC
            .popoverPresentationController {
            popover.sourceView = topVC.view
            popover.sourceRect = CGRect(
                x: topVC.view.bounds.midX,
                y: topVC.view.bounds.midY,
                width: 0, height: 0)
        }

        topVC.present(activityVC, animated: true)
    }

    private func formatted(_ value: Double) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.maximumFractionDigits = 0
        return formatter.string(
            from: NSNumber(value: value)) ?? "0"
    }
}
